### ISSUE TITLE
Bug Report | On Player Use Command

### ISSUE THREAD

**Issue by HackHsda** [micartey/Cardinal-Anticheat#157]
What type of bug you want to report? Describe it here
Command

When does the bug occurr?
When the player uses the command/CAC report

Cardinal Version:
1.0006
Spigot Version:
1.8.9

> **Attached Files  (Required)**
![53COVYX WNIQKOR 0@JVPEE](https://user-images.githubusercontent.com/122268693/211285241-d0201eaa-2878-447f-9aa1-c07de1e57679.png)

**Comment by micartey** [comment]
This is not a bug, but an intentional decision. 

Cardinal Anticheat is closed source and to support as many users and systems as possible I abstracted the database.
This abstraction is called a `dialect`. More [[here]](https://github.com/micartey/Cardinal-Anticheat#custom-ban-manager) 

You can create your own dialect by following the [documentation](https://github.com/micartey/Cardinal-Anticheat/blob/master/DIALECT.md) or if you want to use MySQL you can download a prebuild extension [[here]](https://github.com/micartey/Cardinal-Anticheat/blob/master/dialects/MariaDialect.jar)

NOTE: Extensions are not put inside the `plugins` directory. Instead, they are put inside ``plugins/CAC/addons`
